spring:
  rabbitmq:
    #host: http://122.51.246.240/
    host: http://127.0.0.1/
    port: 15672
    username: admin
    password: 1225dmf1212.
    virtual-host: /
    # 开启发送方确认机制
    publisher-confirms: true
    # 开启发送方返回机制
    publisher-returns: true
    listener:
      simple:
        # 消费者最小数量
        concurrency: 1
        # 消费者最大数量
        max-concurrency: 10
        # 每次从队列中获取的消息数量
        prefetch: 1
        # 消费者自动启动
        auto-startup: true
        # 被拒绝的消息重新进入队列
        default-requeue-rejected: true
        # 签收模式：手动签收
        acknowledge-mode: manual
  profiles:
    active: prod
  cache:
    ehcache:
      config: classpath:ehcache.xml
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
      stat-view-servlet:
        enabled: true
        url-pattern: /*
        reset-enable: false
        login-username: druiduser
        login-password: druidpwd
        allow: 127.0.0.1
    sql-script-encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: smtp.qq.com
    username: 3354627304@qq.com
    password: rnfqmoojsocpcijf
    port: 587
    protocol: smtp

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
jwt:
  token:
    expire:
      time: 30
server:
  port: 9528
app:
  elasticsearch:
    index-name: articles