debug: false
spring:
  datasource:
    url: jdbc:mysql://122.51.246.240:3306/webflash?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: 123qweASD.
  redis:
    host: 122.51.246.240
    port: 6379
    password:  123qweasd. # 如果没有密码可以省略
    database: 0             # 默认数据库索引
    timeout: 3000          # 连接超时时间(毫秒)
    lettuce:
      pool:
        max-active: 20     # 最大连接数
        max-idle: 10       # 最大空闲连接
        min-idle: 5        # 最小空闲连接
        max-wait: 2000     # 获取连接最大等待时间(毫秒)
  jpa:
    hibernate:
      ddl-auto: update
  activiti:
    #    配置为true的时候自动检查resources/bpmn/目录下的工作流定义文件并部署到数据库表中
    check-process-definitions: true
    #    启动的时候配置为true初始化工作流相关表
    database-schema-update: true
    history-level: full
    db-history-used: true
    process-definition-location-prefix: classpath:/bpmn/
server:
  tomcat:
    basedir: /data/app/web-flash/runtime/tmp
urlpath: /data/app/web-flash/runtime/tmp

#nginx配置访问域名http://localhost:15000/
hostUrlNginx: http://localhost:15000/

#数据源配置
DB_mk_oralce: ekp_mid_mysql_test
