spring:
  rabbitmq:
      host: 122.51.246.240
      # host: http://127.0.0.1/http://122.51.246.240:15672/
      port: 5672
      username: admin
      password: 1225dmf1212.
      virtual-host: /
      # 开启发送方确认机制
      #publisher-confirms: true
      # 连接池配置
      connection-timeout: 5000
      cache:
        channel:
          size: 25
        connection:
          mode: channel
      # 发布确认      # 开启发送方返回机制
      publisher-confirm-type: correlated
      publisher-returns: true
      # 消费者配置
      listener:
        simple:
          # 消费者最小数量
          concurrency: 1
          # 消费者最大数量
          max-concurrency: 20
          # 每次从队列中获取的消息数量
          prefetch: 50
          # 消费者自动启动
          auto-startup: true
          # 被拒绝的消息重新进入队列
          default-requeue-rejected: true
          # 签收模式：手动签收
          acknowledge-mode: manual
          retry:
            enabled: true
            max-attempts: 3
            initial-interval: 1000ms
            multiplier: 2.0
            max-interval: 10000ms
  profiles:
    active: prod
  cache:
    ehcache:
      config: classpath:ehcache.xml
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
      stat-view-servlet:
        enabled: true
        url-pattern: /*
        reset-enable: false
        login-username: druiduser
        login-password: druidpwd
        allow: 127.0.0.1
    sql-script-encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: smtp.qq.com
    username: 3354627304@qq.com
    password: rnfqmoojsocpcijf
    port: 587
    protocol: smtp

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  wx:
    secret: 0448e47a39650a17da133394ee393b81
    appid: wx2224ac6c80008d91
jwt:
  token:
    expire:
      time: 30
server:
  port: 9528
app:
  elasticsearch:
    index-name: articles